# IMPORTNG ALL THE LIBRARIES.

In [3]:
import nltk
import seaborn as sns
import math
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

# LOADING THE DATASET.

In [4]:
data=pd.read_excel(r"C:\Users\pc\OneDrive\Desktop\MOVIE_DATASET_FINAL..xlsx")

In [5]:
data=data.drop('Column1',axis=1)

CHECKING THE DATASET FOR NAN VALUES.

In [6]:
data.isna().sum()

movie_id     0
title        0
year        23
genre        0
rating       0
dtype: int64

REMVOVIG THE NAN ROWS DUE TO AVAILABILITY OF HUGE DATASET.

In [7]:
data=data.dropna()

In [8]:
data.shape

(9719, 5)

In [9]:
data.head()

movie_id                        title    year  \
0         1                    Toy Story  1995.0   
1         2                      Jumanji  1995.0   
2         3             Grumpier Old Men  1995.0   
3         4            Waiting to Exhale  1995.0   
4         5  Father of the Bride Part II  1995.0   

                                         genre    rating  
0  Adventure|Animation|Children|Comedy|Fantasy  3.920930  
1                   Adventure|Children|Fantasy  3.431818  
2                               Comedy|Romance  3.259615  
3                         Comedy|Drama|Romance  2.357143  
4                                       Comedy  3.071429

In [10]:
data['genre']=[i.replace('|',' ')for i in data['genre']]

In [11]:
# CONVERTING YEAR TO STRNG TO ADD THE FEATURES.
data['year']=[str(int(i))for i in data['year']]

In [12]:
data['rating']=[str(round(i))for i in data['rating']]

In [13]:
data.head()

movie_id                        title  year  \
0         1                    Toy Story  1995   
1         2                      Jumanji  1995   
2         3             Grumpier Old Men  1995   
3         4            Waiting to Exhale  1995   
4         5  Father of the Bride Part II  1995   

                                         genre rating  
0  Adventure Animation Children Comedy Fantasy      4  
1                   Adventure Children Fantasy      3  
2                               Comedy Romance      3  
3                         Comedy Drama Romance      2  
4                                       Comedy      3

In [14]:
data['model_feature']= data['genre']+" "+data['title']

In [15]:
data.head()

movie_id                        title  year  \
0         1                    Toy Story  1995   
1         2                      Jumanji  1995   
2         3             Grumpier Old Men  1995   
3         4            Waiting to Exhale  1995   
4         5  Father of the Bride Part II  1995   

                                         genre rating  \
0  Adventure Animation Children Comedy Fantasy      4   
1                   Adventure Children Fantasy      3   
2                               Comedy Romance      3   
3                         Comedy Drama Romance      2   
4                                       Comedy      3   

                                       model_feature  
0  Adventure Animation Children Comedy Fantasy To...  
1                 Adventure Children Fantasy Jumanji  
2                    Comedy Romance Grumpier Old Men  
3             Comedy Drama Romance Waiting to Exhale  
4                 Comedy Father of the Bride Part II

In [16]:
featured_data=pd.DataFrame(data)

In [17]:
featured_data.shape

(9719, 6)

# LOADING THE LINK DATASET TO GET THE TMDb ID OF A MOVIE WHICH IS USED TO GET THE POSTER LINK FROM THE TMDb API.

In [18]:
link=pd.read_csv(r"C:\Users\pc\Downloads\ml-latest-small\ml-latest-small\links.csv")
d=np.array(link)
link.shape

(9742, 3)

In [19]:
link.head()

movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [20]:
c=0
idx=[]
for i in np.array(link.isna()): # THIS WILL AN NUMPY ARRAY WITH INDEX AND WEATHER THE ROW HAS 'TRUE' NAN OR 'FALSE' NOT HAVE NAN.

     if i[2]== True:
        idx.append(c) # ADDING THSOE VALUES WHICH ARE HAVING NAN VALUES TO REMVOE FROM LINK AS WELL AS THE MOVIE DATASET LOADED INITIALLY.
     c=c+1 

d=[int(link.iloc[i].movieId) for i in idx] # TAKING THE MOVIE ID OF THE ROW WHCIH CONTAINED THE NAN VALUE SO THAT WE CAN FIND THOSE MOVIES ON THE BASIS OF MOVIE-ID AND THEN REMOVE THEM.
d

[791, 1107, 2851, 4051, 26587, 32600, 40697, 79299]

In [21]:
movie_id=[]
for i in np.array(featured_data['movie_id']):
    if i in d:
        print('yes')
    else:
        movie_id.append(i)

yes
yes
yes
yes
yes
yes
yes


SO OUT OF 8 MOVIES WHICH WERE HAVING NAN VALUES IN THE LINK DATASET 7 ARE THERE IN THE FEATURED_DATASET.

In [22]:
len(movie_id)

9712

CREATING A LIST FOR TMDB-ID FOR MOVIES WHICH WERE THERE IN THE FEATURED DATASET AND ALSO WHICH ARE NOT HAVING VALUES OF NAN IN LINK DATASET.

In [23]:
TMDb_id= [i[2] for i in np.array(link) if i[0] in movie_id]
         

CREATING THE DATAFRAME FOR THE TMDbID.

In [24]:
pd.DataFrame(TMDb_id).to_pickle('TMDbId.pkl')

In [25]:
d1=[]
for i in d:
    d1.append(np.array(featured_data.index[[featured_data['movie_id']==i]]))  # FINDING THE ROW OF THE GIVEN MOVIES WHCIH ARE HAVING NAN IN LINK DATASET.
print(d1[6])
del d1[6]
d1

[]


c:\Users\pc\anaconda3\lib\site-packages\pandas\core\indexes\base.py:5069: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  result = getitem(key)


[array([624], dtype=int64),
 array([843], dtype=int64),
 array([2141], dtype=int64),
 array([3027], dtype=int64),
 array([5532], dtype=int64),
 array([5854], dtype=int64),
 array([7382], dtype=int64)]

In [26]:
# APPENDIG ALL THESE INDEX IN THE g LIST SO THAT WE CAN REMOVE THOSE SPECIFIC ROWS FROM THE FEATURED DATASET AND THUS CREATE THE FINAL DATASET. 
g=[]
for i in range(0,len(d1)):
        g.append(int((d1[i][0])))
    

REMOVING THE ROW AND CREATING A FINAL DATASET.

In [27]:
featured_data.drop(g,axis=0,inplace=True)

In [28]:
featured_data.head()

movie_id                        title  year  \
0         1                    Toy Story  1995   
1         2                      Jumanji  1995   
2         3             Grumpier Old Men  1995   
3         4            Waiting to Exhale  1995   
4         5  Father of the Bride Part II  1995   

                                         genre rating  \
0  Adventure Animation Children Comedy Fantasy      4   
1                   Adventure Children Fantasy      3   
2                               Comedy Romance      3   
3                         Comedy Drama Romance      2   
4                                       Comedy      3   

                                       model_feature  
0  Adventure Animation Children Comedy Fantasy To...  
1                 Adventure Children Fantasy Jumanji  
2                    Comedy Romance Grumpier Old Men  
3             Comedy Drama Romance Waiting to Exhale  
4                 Comedy Father of the Bride Part II

# CREATING THE CORPUS FOR THE CREATED MODLE FEATURES.

In [29]:
corpus=[]
a=featured_data['model_feature'].apply(lambda x:corpus.append(x))
#corpus created would be in the form of list.

CONVERTING THE CORPUS INTO THE STRING FORMAT SO THAT I CAN SPLIT THE WORDS AND THEN CREATE A VOCABULARY OUT OF THESE FOLLOWING CORPUS.

In [30]:
corpus_=' '.join(corpus)

# CREATNIG THE CORPUS DICTIONARY OR THE VOCABULARY.

In [31]:
corpus_dictionary=sorted(list(set(corpus_.split(' '))))
corpus_dictionary=list(enumerate(corpus_dictionary))

# INITIALIZING THE VECTORS DIMENSIONS TO APPLY BAG OF WORDS.

In [32]:
vectors=np.zeros((featured_data.shape[0],len(corpus_dictionary)))

# APPLYING THE BAG OF WORDS AND CREATING THE VECTORS.

In [33]:
for i in range(0,9712,1):
    for word in corpus_dictionary:
        if word[1] in corpus[i].split(' '):
            
            vectors[i][word[0]]=1
        else:
            vectors[i][word[0]]=0
    

# CREATING THE CLASS FOR THE KNN MODEL.

In [34]:
class KNearestNeighbours():
    def __init__(self,k=6):
        self.k=k
    def initilize_dataset(self,X):
        self.x=X
        self.similarity=self.cosine_similarity(self.x)
        return(self.similarity)
        
    def cosine_similarity(self,x):
        csv=cosine_similarity(x)
        return(csv)
    def recomend(self,movie):
        movie_index=featured_data[featured_data['title']==movie].index[0]
        movie_distance=self.similarity[movie_index]
        movie_list=sorted(list(enumerate(movie_distance)),reverse=True,key=lambda x:x[1])[1:self.k]
        for i in movie_list:
            print(featured_data.iloc[i[0]].title)

# CREATING THE OBJECT AND USING IT'S ATTRIBUTES.

In [35]:
KNN=KNearestNeighbours(7)
similarity_vectors=KNN.initilize_dataset(vectors)

In [36]:
similarity_vectors.shape

(9712, 9712)

# RECOMMENDING THE MOVIES.

In [37]:
KNN.recomend("Toy Story")

Toy Story 2
Toy Story 3
Antz
Turbo
Moana
Shrek


# STORING THE SIMILARITY VECTORS FOR FLASK APP IMPLEMENTATION.

In [38]:
pd.DataFrame(similarity_vectors).to_pickle('vectors.pkl')

In [39]:
movie_names=[]
for i in np.array(featured_data):
    if i[0] in movie_id:
        movie_names.append(i[1])

In [40]:
pd.DataFrame(movie_names).to_pickle('movie_names.pkl')

In [41]:
similarity=np.array(pd.read_pickle(r'C:\Users\pc\OneDrive\Desktop\MOVIE RECOMENDATION SYSTEM\model\vectors.pkl'))

In [42]:
similarity.shape

(9712, 9712)

In [43]:
a=pd.read_pickle(r'C:\Users\pc\OneDrive\Desktop\MOVIE_LENS\MODEL\TMDbId.pkl')

In [44]:
np.array(a)

array([[   862.],
       [  8844.],
       [ 15602.],
       ...,
       [479308.],
       [483455.],
       [ 37891.]])